# Generated by Django 5.2.12 on 2026-03-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_crew_train_traintype_journey_train_train_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='role',
            field=models.CharField(default='driver', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crew',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journey',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='train',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='traintype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
