# Generated by Django 5.2.12 on 2026-03-26 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_order_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='arrival_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='journey',
            name='departure_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='journey',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journeys', to='station.route'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journeys', to='station.train'),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_to', to='station.station'),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_from', to='station.station'),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trains', to='station.traintype'),
        ),
    ]
